-- MySQL Script generated by MySQL Workbench
-- 05/18/16 08:26:44
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema easyfooddb
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema easyfooddb
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `easyfooddb` DEFAULT CHARACTER SET utf8 COLLATE utf8_general_ci ;
USE `easyfooddb` ;

-- -----------------------------------------------------
-- Table `easyfooddb`.`regioni`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `easyfooddb`.`regioni` (
  `codRegione` VARCHAR(3) NOT NULL,
  `nomeRegione` VARCHAR(30) NOT NULL,
  PRIMARY KEY (`codRegione`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `easyfooddb`.`province`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `easyfooddb`.`province` (
  `codProvincia` VARCHAR(2) NOT NULL,
  `nomeProvincia` VARCHAR(35) NOT NULL,
  `codRegione` VARCHAR(3) NOT NULL,
  PRIMARY KEY (`codProvincia`),
  INDEX `codRegioni_idx` (`codRegione` ASC),
  CONSTRAINT `codRegioni`
    FOREIGN KEY (`codRegione`)
    REFERENCES `easyfooddb`.`regioni` (`codRegione`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `easyfooddb`.`comuni`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `easyfooddb`.`comuni` (
  `codCatastale` VARCHAR(4) NOT NULL,
  `nomeComune` VARCHAR(30) NOT NULL,
  `cap` INT NOT NULL,
  `codProvincia` VARCHAR(2) NOT NULL,
  PRIMARY KEY (`codCatastale`),
  INDEX `codProvincia_idx` (`codProvincia` ASC),
  CONSTRAINT `codProvincia`
    FOREIGN KEY (`codProvincia`)
    REFERENCES `easyfooddb`.`province` (`codProvincia`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `easyfooddb`.`ristoranti`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `easyfooddb`.`ristoranti` (
  `codRistorante` INT NOT NULL AUTO_INCREMENT,
  `indirizzo` VARCHAR(50) NOT NULL,
  `nomeRistorante` VARCHAR(50) NOT NULL,
  `longitudine` DOUBLE NULL,
  `latitudine` DOUBLE NULL,
  `descrizione` TEXT NULL,
  `codCatastale` VARCHAR(45) NOT NULL,
  `telRistornate` VARCHAR(20) NULL,
  `emailRistorante` VARCHAR(45) NULL,
  PRIMARY KEY (`codRistorante`),
  INDEX `fk_ristoranti_comuni1_idx` (`codCatastale` ASC),
  CONSTRAINT `fk_ristoranti_comuni1`
    FOREIGN KEY (`codCatastale`)
    REFERENCES `easyfooddb`.`comuni` (`codCatastale`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `easyfooddb`.`cibi`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `easyfooddb`.`cibi` (
  `codCiboPrezzo` INT NOT NULL AUTO_INCREMENT,
  `nomeCibo` VARCHAR(45) NULL,
  `prezzoCibo` FLOAT NULL,
  PRIMARY KEY (`codCiboPrezzo`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `easyfooddb`.`menu`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `easyfooddb`.`menu` (
  `codCibo` INT NOT NULL,
  `codRistorante` INT NOT NULL,
  INDEX `fk_menu_cibi1_idx` (`codCibo` ASC),
  INDEX `fk_menu_ristoranti1_idx` (`codRistorante` ASC),
  PRIMARY KEY (`codCibo`, `codRistorante`),
  CONSTRAINT `codiceCibo`
    FOREIGN KEY (`codCibo`)
    REFERENCES `easyfooddb`.`cibi` (`codCiboPrezzo`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `codiceRistorante`
    FOREIGN KEY (`codRistorante`)
    REFERENCES `easyfooddb`.`ristoranti` (`codRistorante`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `easyfooddb`.`utente`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `easyfooddb`.`utente` (
  `codUtente` INT NOT NULL AUTO_INCREMENT,
  `nome` VARCHAR(45) NOT NULL,
  `cognome` VARCHAR(45) NOT NULL,
  `indirizzo` VARCHAR(45) NULL,
  `emailUtente` VARCHAR(45) NOT NULL,
  `codCatastale` VARCHAR(4) NULL,
  `telUtente` VARCHAR(20) NULL,
  `utenteConfermato` TINYINT(1) NOT NULL DEFAULT 0,
  `username` VARCHAR(45) NOT NULL,
  `password` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`codUtente`),
  INDEX `fk_utente_comuni1_idx` (`codCatastale` ASC),
  UNIQUE INDEX `emailUtente_UNIQUE` (`emailUtente` ASC),
  UNIQUE INDEX `username_UNIQUE` (`username` ASC),
  CONSTRAINT `fk_utente_comuni1`
    FOREIGN KEY (`codCatastale`)
    REFERENCES `easyfooddb`.`comuni` (`codCatastale`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `easyfooddb`.`credenziali`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `easyfooddb`.`credenziali` (
  `username` VARCHAR(45) NOT NULL,
  `password` VARCHAR(45) NOT NULL,
  `codUtente` INT NOT NULL,
  PRIMARY KEY (`username`),
  INDEX `fk_credenziali_utente1_idx` (`codUtente` ASC),
  CONSTRAINT `codUtente`
    FOREIGN KEY (`codUtente`)
    REFERENCES `easyfooddb`.`utente` (`codUtente`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `easyfooddb`.`proprietari`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `easyfooddb`.`proprietari` (
  `codRistorante` INT NOT NULL,
  `codUtente` INT NOT NULL,
  PRIMARY KEY (`codUtente`, `codRistorante`),
  INDEX `fk_Proprietari_ristoranti1_idx` (`codRistorante` ASC),
  INDEX `fk_Proprietari_utente1_idx` (`codUtente` ASC),
  CONSTRAINT `fk_Proprietari_ristoranti1`
    FOREIGN KEY (`codRistorante`)
    REFERENCES `easyfooddb`.`ristoranti` (`codRistorante`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Proprietari_utente1`
    FOREIGN KEY (`codUtente`)
    REFERENCES `easyfooddb`.`utente` (`codUtente`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `easyfooddb`.`tipologia_locale`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `easyfooddb`.`tipologia_locale` (
  `codTipo` INT NOT NULL AUTO_INCREMENT,
  `Tipo` VARCHAR(30) NOT NULL,
  PRIMARY KEY (`codTipo`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `easyfooddb`.`valutazioni`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `easyfooddb`.`valutazioni` (
  `codRistorante` INT NOT NULL,
  `codUtente` INT NOT NULL,
  `valutazione` SMALLINT(1) NOT NULL,
  `titoloCommento` VARCHAR(120) NULL,
  `commento` TINYTEXT NULL,
  INDEX `fk_Valutazioni_ristoranti1_idx` (`codRistorante` ASC),
  INDEX `fk_Valutazioni_utente1_idx` (`codUtente` ASC),
  PRIMARY KEY (`codRistorante`, `codUtente`),
  CONSTRAINT `fk_Valutazioni_ristoranti1`
    FOREIGN KEY (`codRistorante`)
    REFERENCES `easyfooddb`.`ristoranti` (`codRistorante`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Valutazioni_utente1`
    FOREIGN KEY (`codUtente`)
    REFERENCES `easyfooddb`.`utente` (`codUtente`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `easyfooddb`.`immagini`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `easyfooddb`.`immagini` (
  `codImmagine` INT NOT NULL AUTO_INCREMENT,
  `path` VARCHAR(255) NOT NULL,
  `isLogo` TINYINT(1) NOT NULL DEFAULT 0,
  `codRistorante` INT NOT NULL,
  PRIMARY KEY (`codImmagine`),
  INDEX `fk_immagini_ristoranti1_idx` (`codRistorante` ASC),
  CONSTRAINT `fk_immagini_ristoranti1`
    FOREIGN KEY (`codRistorante`)
    REFERENCES `easyfooddb`.`ristoranti` (`codRistorante`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `easyfooddb`.`tipologie`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `easyfooddb`.`tipologie` (
  `codTipo` INT NOT NULL,
  `codRistorante` INT NOT NULL,
  INDEX `fk_tipologie_tipologia_locale1_idx` (`codTipo` ASC),
  INDEX `fk_tipologie_ristoranti1_idx` (`codRistorante` ASC),
  PRIMARY KEY (`codTipo`, `codRistorante`),
  CONSTRAINT `fk_tipologie_tipologia_locale1`
    FOREIGN KEY (`codTipo`)
    REFERENCES `easyfooddb`.`tipologia_locale` (`codTipo`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_tipologie_ristoranti1`
    FOREIGN KEY (`codRistorante`)
    REFERENCES `easyfooddb`.`ristoranti` (`codRistorante`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `easyfooddb`.`Orari`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `easyfooddb`.`Orari` (
  `codOrario` INT NOT NULL AUTO_INCREMENT,
  `codRistorante` INT NOT NULL,
  `giorno` INT NULL,
  `apertura` TIME NULL,
  `chiusura` TIME NULL,
  INDEX `fk_Orari_ristoranti1_idx` (`codRistorante` ASC),
  PRIMARY KEY (`codOrario`),
  CONSTRAINT `fk_Orari_ristoranti1`
    FOREIGN KEY (`codRistorante`)
    REFERENCES `easyfooddb`.`ristoranti` (`codRistorante`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `easyfooddb`.`Giorni`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `easyfooddb`.`Giorni` (
  `codGiorno` INT NOT NULL,
  `giorno` VARCHAR(10) NULL,
  PRIMARY KEY (`codGiorno`))
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
